"""
PentPython Report Generator
Generates standardized PDF and Markdown security reports
"""

import os
import json
from datetime import datetime
from typing import List, Dict, Any

# Try to import PDF libraries
try:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
    from reportlab.lib.colors import HexColor
    from reportlab.lib.enums import TA_CENTER, TA_LEFT
    PDF_AVAILABLE = True
except ImportError:
    PDF_AVAILABLE = False

class SecurityReport:
    """Generates standardized security assessment reports."""
    
    def __init__(self, target: str):
        self.target = target
        self.date = datetime.now().strftime('%Y-%m-%d %H:%M')
        self.findings = []
        self.scan_results = {}
        
    def add_finding(self, title: str, severity: str, description: str, 
                   evidence: str = "", recommendation: str = "", category: str = ""):
        """Add a security finding to the report."""
        self.findings.append({
            "title": title,
            "severity": severity.upper(),
            "category": category,
            "description": description,
            "evidence": evidence,
            "recommendation": recommendation
        })
    
    def add_scan_result(self, tool_name: str, result: str):
        """Add raw scan results."""
        self.scan_results[tool_name] = result
    
    def _severity_order(self, finding):
        """Sort findings by severity."""
        order = {"CRITICAL": 0, "HIGH": 1, "MEDIUM": 2, "LOW": 3, "INFO": 4}
        return order.get(finding["severity"], 5)
    
    def generate_markdown(self) -> str:
        """Generate a markdown report."""
        self.findings.sort(key=self._severity_order)
        
        # Count by severity
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for f in self.findings:
            counts[f["severity"]] = counts.get(f["severity"], 0) + 1
        
        report = f"""# Security Assessment Report

## Executive Summary

| **Target** | {self.target} |
|------------|---------------|
| **Date** | {self.date} |
| **Generated By** | PentPython Security Scanner |

---

## Findings Summary

| Severity | Count |
|----------|-------|
| 🔴 Critical | {counts['CRITICAL']} |
| 🟠 High | {counts['HIGH']} |
| 🟡 Medium | {counts['MEDIUM']} |
| 🔵 Low | {counts['LOW']} |
| ⚪ Info | {counts['INFO']} |

**Total Findings: {len(self.findings)}**

---

## Risk Rating

"""
        # Calculate risk rating
        if counts['CRITICAL'] > 0:
            report += "**Overall Risk: 🔴 CRITICAL**\n\nImmediate action required. Critical vulnerabilities detected.\n\n"
        elif counts['HIGH'] > 0:
            report += "**Overall Risk: 🟠 HIGH**\n\nSignificant vulnerabilities require prompt attention.\n\n"
        elif counts['MEDIUM'] > 0:
            report += "**Overall Risk: 🟡 MEDIUM**\n\nSome security improvements recommended.\n\n"
        elif counts['LOW'] > 0:
            report += "**Overall Risk: 🔵 LOW**\n\nMinor issues identified. Good security posture.\n\n"
        else:
            report += "**Overall Risk: ✅ MINIMAL**\n\nNo significant vulnerabilities detected.\n\n"
        
        report += "---\n\n## Detailed Findings\n\n"
        
        # Add findings
        for i, finding in enumerate(self.findings, 1):
            severity_icon = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🔵", "INFO": "⚪"}.get(finding["severity"], "⚪")
            
            report += f"""### {i}. {finding['title']}

| | |
|---|---|
| **Severity** | {severity_icon} {finding['severity']} |
| **Category** | {finding.get('category', 'General')} |

**Description:**
{finding['description']}

"""
            if finding.get('evidence'):
                report += f"""**Evidence:**
```
{finding['evidence']}
```

"""
            if finding.get('recommendation'):
                report += f"""**Recommendation:**
{finding['recommendation']}

"""
            report += "---\n\n"
        
        # Add scan results
        if self.scan_results:
            report += "## Appendix: Scan Results\n\n"
            for tool, result in self.scan_results.items():
                report += f"### {tool}\n```\n{result}\n```\n\n"
        
        # Add footer
        report += """---

## Disclaimer

This security assessment was performed using automated scanning tools. While these tools can identify many common vulnerabilities, they may not detect all security issues. Manual testing and code review are recommended for comprehensive security coverage.

**Important:** Only perform security testing on systems you have explicit authorization to test.

---

*Report generated by PentPython Security Scanner*
"""
        return report
    
    def generate_pdf(self, output_path: str) -> str:
        """Generate a PDF report."""
        if not PDF_AVAILABLE:
            return "Error: reportlab not installed. Run: pip install reportlab"
        
        try:
            doc = SimpleDocTemplate(output_path, pagesize=A4,
                                   rightMargin=72, leftMargin=72,
                                   topMargin=72, bottomMargin=72)
            
            styles = getSampleStyleSheet()
            
            # Custom styles
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=HexColor('#1a1a2e'),
                spaceAfter=30,
                alignment=TA_CENTER
            )
            
            heading_style = ParagraphStyle(
                'CustomHeading',
                parent=styles['Heading2'],
                fontSize=16,
                textColor=HexColor('#16213e'),
                spaceBefore=20,
                spaceAfter=10
            )
            
            normal_style = ParagraphStyle(
                'CustomNormal',
                parent=styles['Normal'],
                fontSize=11,
                leading=14
            )
            
            elements = []
            
            # Title
            elements.append(Paragraph("Security Assessment Report", title_style))
            elements.append(Spacer(1, 20))
            
            # Target info
            info_data = [
                ["Target:", self.target],
                ["Date:", self.date],
                ["Scanner:", "PentPython"]
            ]
            info_table = Table(info_data, colWidths=[100, 350])
            info_table.setStyle(TableStyle([
                ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 0), (-1, -1), 11),
                ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
                ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ]))
            elements.append(info_table)
            elements.append(Spacer(1, 30))
            
            # Summary
            elements.append(Paragraph("Findings Summary", heading_style))
            
            counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
            for f in self.findings:
                counts[f["severity"]] = counts.get(f["severity"], 0) + 1
            
            summary_data = [
                ["Severity", "Count"],
                ["Critical", str(counts['CRITICAL'])],
                ["High", str(counts['HIGH'])],
                ["Medium", str(counts['MEDIUM'])],
                ["Low", str(counts['LOW'])],
                ["Info", str(counts['INFO'])],
                ["Total", str(len(self.findings))]
            ]
            
            summary_table = Table(summary_data, colWidths=[150, 100])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), HexColor('#1a1a2e')),
                ('TEXTCOLOR', (0, 0), (-1, 0), HexColor('#ffffff')),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, -1), 11),
                ('BACKGROUND', (0, 1), (-1, 1), HexColor('#ff4444') if counts['CRITICAL'] > 0 else HexColor('#f0f0f0')),
                ('BACKGROUND', (0, 2), (-1, 2), HexColor('#ff8c00') if counts['HIGH'] > 0 else HexColor('#f0f0f0')),
                ('BACKGROUND', (0, 3), (-1, 3), HexColor('#ffd700') if counts['MEDIUM'] > 0 else HexColor('#f0f0f0')),
                ('GRID', (0, 0), (-1, -1), 1, HexColor('#cccccc')),
                ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ]))
            elements.append(summary_table)
            elements.append(PageBreak())
            
            # Detailed findings
            elements.append(Paragraph("Detailed Findings", heading_style))
            
            self.findings.sort(key=self._severity_order)
            
            for i, finding in enumerate(self.findings, 1):
                elements.append(Paragraph(f"{i}. {finding['title']}", heading_style))
                elements.append(Paragraph(f"<b>Severity:</b> {finding['severity']}", normal_style))
                elements.append(Paragraph(f"<b>Category:</b> {finding.get('category', 'General')}", normal_style))
                elements.append(Spacer(1, 10))
                elements.append(Paragraph(f"<b>Description:</b><br/>{finding['description']}", normal_style))
                
                if finding.get('evidence'):
                    elements.append(Spacer(1, 5))
                    elements.append(Paragraph(f"<b>Evidence:</b><br/>{finding['evidence'][:500]}", normal_style))
                
                if finding.get('recommendation'):
                    elements.append(Spacer(1, 5))
                    elements.append(Paragraph(f"<b>Recommendation:</b><br/>{finding['recommendation']}", normal_style))
                
                elements.append(Spacer(1, 20))
            
            # Build PDF
            doc.build(elements)
            
            return f"PDF report saved to: {output_path}"
            
        except Exception as e:
            return f"Error generating PDF: {str(e)}"
    
    def save(self, output_dir: str = ".") -> Dict[str, str]:
        """Save both markdown and PDF reports."""
        results = {}
        
        # Generate timestamp for filenames
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        safe_target = self.target.replace("://", "_").replace("/", "_").replace(".", "_")[:30]
        
        # Save markdown
        md_path = os.path.join(output_dir, f"report_{safe_target}_{timestamp}.md")
        with open(md_path, 'w', encoding='utf-8') as f:
            f.write(self.generate_markdown())
        results['markdown'] = md_path
        
        # Save PDF
        if PDF_AVAILABLE:
            pdf_path = os.path.join(output_dir, f"report_{safe_target}_{timestamp}.pdf")
            pdf_result = self.generate_pdf(pdf_path)
            results['pdf'] = pdf_path if "saved" in pdf_result else pdf_result
        else:
            results['pdf'] = "PDF generation not available (install reportlab)"
        
        return results


def create_report(target: str, findings: List[Dict], scan_results: Dict[str, str] = None) -> SecurityReport:
    """Helper function to create a report from findings."""
    report = SecurityReport(target)
    
    for finding in findings:
        report.add_finding(
            title=finding.get('title', finding.get('type', 'Unknown')),
            severity=finding.get('severity', 'INFO'),
            description=finding.get('description', finding.get('detail', '')),
            evidence=finding.get('evidence', ''),
            recommendation=finding.get('recommendation', ''),
            category=finding.get('category', '')
        )
    
    if scan_results:
        for tool, result in scan_results.items():
            report.add_scan_result(tool, result)
    
    return report
